            <div id="nav-felt">
            	<ul> <!-- Hvert link i nav-baren leder til en ny side, alle med samme CSS-fil og dermed samme design -->
  			<li><a href="#home"><h3>Home</h3></a></li>
  			<li><a href="#news"><h3>News</h3></a></li>
  			<li><a href="#contact"><h3>Contact</h3></a></li>
  			<li><a href="#about"><h3>About</h3></a></li>
  			<li><a href="#1"><h3>Info</h3></a></li>
  			<li><a href="#2"><h3>Om opgaven</h3></a></li>
  			<li><a href="#3"><h3>3</h3></a></li>
  			<li><a href="#4"><h3>4</h3></a></li>
  			<li><a href="#5"><h3>5</h3></a></li>
  			<li><a href="#6"><h3>6</h3></a></li>
  			<li><a href="#7"><h3>7</h3></a></li>
  			<li><a href="#8"><h3>8</h3></a></li>
  			<li><a href="#9"><h3>9</h3></a></li>
  			<li><a href="#10"><h3>10</h3></a></li>
  			<li><a href="#11"><h3>11</h3></a></li>
  			<li><a href="#12"><h3>12</h3></a></li>
  			<li><a href="#13"><h3>13</h3></a></li>
  			<li><a href="#14"><h3>14</h3></a></li>
  			<li><a href="#15"><h3>15</h3></a></li>
  			<li><a href="#16"><h3>16</h3></a></li>
  			<li><a href="#17"><h3>17</h3></a></li>
  			<li><a href="#18"><h3>18</h3></a></li>
  			<li><a href="#19"><h3>19</h3></a></li>
  			<li><a href="#20"><h3>20</h3></a></li>
  			<li><a href="#21"><h3>21</h3></a></li>
  			<li><a href="#kilder"><h3>Kilder</h3></a></li>
				</ul> 
            </div>